CREATE TABLE IF NOT EXISTS `XH_BOOK` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `author` VARCHAR(64) DEFAULT NULL,
  `brief` VARCHAR(2048) DEFAULT NULL,
  `cover` VARCHAR(1024) DEFAULT NULL,
  `type` VARCHAR(64) DEFAULT NULL,
  `adaptAge` VARCHAR(64) DEFAULT NULL,
  `invNum` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100001 DEFAULT CHARSET=utf8;